spring:
  application:
    name: abasteceai-app
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/abasteceai-app
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
        fomart_sql: true
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
